coverage:
  status:
    project:
      default:
        target: 90%    # the required coverage value
        threshold: 10%
comment: 
  behavior: default
  layout: "reach,diff,flags,tree"
  require_changes: false